### ISSUE TITLE
language inconsistencies

### ISSUE THREAD

**Issue by elvisisvan** [Dapp-Learning-DAO/Dapp-Learning#1007]
since the _typing_ and _naming of files_ and **issues** are all written in english, why not write the documentations in english too? is this english/chinese combination worth the complication?

**Comment by yanyanho** [comment]
Sorry ,  Our core contributors are all  from Chinese. We just translated the first 30 tasks into English. Welcome to participate in  translating the project into English. We want our project could help more developers from all around the world.
