### ISSUE TITLE
B视频不见了

### ISSUE THREAD

**Issue by sponing** [Dapp-Learning-DAO/Dapp-Learning#1173]
同时在 BiliBili 上有上传本样例代码的讲解演示:
https://www.bilibili.com/video/BV1Y44y1r7E6/  视频不见了

**Comment by yanyanho** [comment]
请问这是哪个readme的内容，麻烦提供相信信息。

**Comment by stevending1st** [comment]
> 请问这是哪个readme的内容，麻烦提供相应信息。

https://github.com/Dapp-Learning-DAO/Dapp-Learning/blob/9659a3a572981b35e9b555f05cd8143f58f8e55d/basic/01-web3js-deploy/README-cn.md?plain=1#L14-L15

**Comment by sponing** [comment]
- 同时在 BiliBili 上有上传本样例代码的讲解演示:    
 https://www.bilibili.com/video/BV1Y44y1r7E6/

**Comment by yanyanho** [comment]
> * 同时在 BiliBili 上有上传本样例代码的讲解演示:
>   https://www.bilibili.com/video/BV1Y44y1r7E6/

视频太老了，后面我们再录制一期吧。欢迎入群交流
