### ISSUE TITLE
Snapshoot

### ISSUE THREAD

**Issue by jhfnetboy** [Dapp-Learning-DAO/Dapp-Learning#232]
clone了snapshot，打算山寨个snapshoot。。。。给我们自己和别人用。。。比较不喜欢必须有eth域名
MIT，开源开放，服务器费用靠捐赠
有想法的加入，一起做
另外未来要介入chainlink，为链上提供后续推动

**Comment by liberhe** [comment]
哈哈，可以帮你接入chainlink。 对了，为啥不直接用snapshot呢？
