### ISSUE TITLE
最近在研究借贷清算，可以认领compound分析

### ISSUE THREAD

**Issue by qiushaoxi** [Dapp-Learning-DAO/Dapp-Learning#260]

**Comment by liberhe** [comment]
Excellent!

**Comment by qiushaoxi** [comment]
> Excellent!

就直接分析提PR是吗

**Comment by loophe** [comment]
我也可以认领，已经完成了compound协议的research，并且fork后启动了新的NFT项目。

**Comment by liberhe** [comment]
> 我也可以认领，已经完成了compound协议的research，并且fork后启动了新的NFT项目。

join our discord and self introduce.  https://discord.gg/cRYNYXqPeR
