### ISSUE TITLE
【建议】搭建文档站点

### ISSUE THREAD

**Issue by D-lyw** [Dapp-Learning-DAO/Dapp-Learning#553]
### 文档站点

建议搭建我们项目的文档站点，原因有以下两点：

+ 随着项目教程任务的不断增多，所有的入门都展示在Dapp-Learning项目的Readme文件中，内容过多，不够清晰直观，单靠一个Readme内容将无法承载说明我们项目的所有内容；

+ 教程项目均在各个项目的文件目录下，用户一般需要在本地查看每个项目教程的Readme文档内容，阅读学习还是不够便利。是否可以把每个项目的教程说明内容，统一移至教程文档站点中，方便用户查看教程类别和各任务的指导教程。

文档站点的实现方式：使用 GitBook 搭建（快速简单）或调研其他更自定义、更健壮的方式

风格参考：
![image](https://user-images.githubusercontent.com/33343571/148398622-1565b9ad-abb1-416e-acc9-3a125ad4b8e3.png)

**Comment by sonichen** [comment]
请问这个有实施吗
