### ISSUE TITLE
uniswap v2: price-impact-too-high

### ISSUE THREAD

**Issue by chunqizhi** [Dapp-Learning-DAO/Dapp-Learning#648]
可以请问一下各位大佬，这个值是如何算出来的啊？

<img width="334" alt="image" src="https://user-images.githubusercontent.com/23360623/158347077-862a4fae-7256-4653-b047-fe7e7174ecf1.png">

**Comment by maroonstar** [comment]
check this out: https://docs.uniswap.org/protocol/concepts/V3-overview/swaps#price-impact
