### ISSUE TITLE
建议优化任务链接

### ISSUE THREAD

**Issue by wp-lai** [Dapp-Learning-DAO/Dapp-Learning#660]
现在的链接是连接到任务目录的 README.md 文件，建议直接链接到任务目录，这样跳转过后既能显示 README，又能方便看到任务目录的文件。

以 `01 deploy contract with web3.js` 任务为例，原始链接 `basic/01-web3js-deploy/README.md` 的效果为
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/6768582/159149126-d0909d67-a32c-471b-b33b-34443e2926f8.png">

若将链接修改为 `basic/01-web3js-deploy` 的效果为
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/6768582/159149144-7ffa3c39-0167-479b-89af-2aa1bee21e5f.png">

修改之后可以方便结合 README 查看对应的文件。

**Comment by liberhe** [comment]
good idea~

**Comment by cacacai** [comment]
怪不得看得我一脸蒙蔽的，我看最下面的链接中都没找到readme中说的文件在那

**Comment by yingjingyang** [comment]
已修改
