### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Gfusss333** [Dapp-Learning-DAO/Dapp-Learning#930]
[]()npm install --save @magic-sdk/admin ```

const { Magic } = require('@magic-sdk/admin');

const mAdmin = new Magic('SECRET_API_KEY'); // ✨

```

**Comment by Gfusss333** [comment]
const { Magic } = require('@magic-sdk/admin');

const mAdmin = new Magic('SECRET_API_KEY'); // ✨

**Comment by liberhe** [comment]
what's this?
