### ISSUE TITLE
05-ethersjs-erc20/web3-vs-ethers  ./deployed/contract.json

### ISSUE THREAD

**Issue by lucbook** [Dapp-Learning-DAO/Dapp-Learning#953]
05-ethersjs-erc20/web3-vs-ethers
index.js
const contracts = require('./deployed/contract.json');
这个路径怎么获取的呢？

**Comment by yingjingyang** [comment]
执行 05-ethersjs-erc20/web3-vs-ethers/compile.js 后会在 05-ethersjs-erc20/web3-vs-ethers 目录下生成这个文件
