### ISSUE TITLE
运行 06-ethersjs-waffle 报错

### ISSUE THREAD

**Issue by lucbook** [Dapp-Learning-DAO/Dapp-Learning#954]
Error: cannot estimate gas; transaction may fail or may require manual gas limit 

    at async Promise.all (index 6) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: processing response erro

    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":48,"error":{"code":-32000,"message":"contract creation code storage out of gas"}}',

**Comment by yingjingyang** [comment]
有加入我们微信群吗，可以加入我们微信群直接聊的
