### ISSUE TITLE
Bug in 01-web3js-depoly, TypeError: Web3 is not a constructor

### ISSUE THREAD

**Issue by Fodesu** [Dapp-Learning-DAO/Dapp-Learning#983]
![图片](https://github.com/Dapp-Learning-DAO/Dapp-Learning/assets/75713465/082c2a4f-796c-4ab3-905c-ee5aec5cc2d6)
![图片](https://github.com/Dapp-Learning-DAO/Dapp-Learning/assets/75713465/75ca06ae-93ae-4644-a6cb-361bc51cec07)

**Comment by 0x-stan** [comment]
Caused by web3 version problem, had fix it at https://github.com/Dapp-Learning-DAO/Dapp-Learning/pull/987
