### ISSUE TITLE
认领DaoHaus task

### ISSUE THREAD

**Issue by jhfnetboy** [Dapp-Learning-DAO/Dapp-Learning#99]
个人在DAO方面做过一些分析，期待自己后面的学习过程和大家分享

**Comment by liberhe** [comment]
great!

**Comment by maroonstar** [comment]
:clap:  :clap: :clap:
认领子任务的小伙伴可以在这里留言 👇

**Comment by jhfnetboy** [comment]
对，欢迎一起分析，已进入DAOhaus的源代码分析阶段，期待有想法的同学早点行动起来~！
并行解构分析后，创建属于我们自己的DAO，开源开放，为全国、全球的996创造在家Home Office，异地全球协作组织~！
不要到我们发Token回溯空投的时候，你再追悔莫及哦~！

**Comment by xrdavies** [comment]
Count me in.
