### ISSUE TITLE
基础预备知识中Rust快学的链接失效了

### ISSUE THREAD

**Issue by sonichen** [Dapp-Learning-DAO/Dapp-Learning#994]

**Comment by sonichen** [comment]
https://github.com/Dapp-Learning-DAO/Dapp-Learning/blob/main/docs/basic-knowledge.md

**Comment by yanyanho** [comment]
do you have any links to recommend?

**Comment by sonichen** [comment]
> do you have any links to recommend?

I think https://course.rs/about-book.html is a good course to learn Rust, I learned Rust in this website. Also, I find the chapter 5 Geth of《以太坊的指南针》is out of date, it contains many mistakes, maybe the Dapp-Learning can note this in the document. Can I pull request for these two problem?
(Dapp-Learning is a good platform to learning Web3.0, now I am leanring Web3.0 with the help of Dapp-Learning, Thank you for your amazing work. I also want to work with your.)

**Comment by liberhe** [comment]
https://course.rs/about-book.html   it is really a good course.  Of course you can fix the two problems and make a pull request.  Thank you for recognising and supporting Dapp  Learning!

**Comment by liberhe** [comment]
> > do you have any links to recommend?
> 
> I think https://course.rs/about-book.html is a good course to learn Rust, I learned Rust in this website. Also, I find the chapter 5 Geth of《以太坊的指南针》is out of date, it contains many mistakes, maybe the Dapp-Learning can note this in the document. Can I pull request for these two problem? (Dapp-Learning is a good platform to learning Web3.0, now I am leanring Web3.0 with the help of Dapp-Learning, Thank you for your amazing work. I also want to work with your.)

add wechat yanyanho666 to join our developer group
